name: Release

on:
  # Manually trigger the workflow
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run release from'
        required: true
        default: 'main'
        type: string

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Checkout the branch specified in the trigger, or the head ref of the PR
          ref: ${{ github.event.inputs.branch || github.ref }}
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # Run our custom release script that builds and publishes
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Display Release Information
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "🎉 Published packages to npm!"
          echo "Published packages: ${{ steps.changesets.outputs.publishedPackages }}" 